### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by zimt28** [kadirahq/meteor-graphql#1]
Do all browsers support [`Promise`](https://github.com/kadirahq/meteor-graphql/blob/f1b9c2dc45a5998b01a356e62dcda1781f0c2e6c/client/lokka_transport.js#L24)s? Maybe use a polyfill?

**Comment by arunoda** [comment]
I hope that's supplied by the ecmascript polyfill. Isn't it ?

**Comment by zimt28** [comment]
I see you have [opened a thread on the Meteor Forums](https://forums.meteor.com/t/meteor-1-2-promise-pollyfill/15410), just to keep everyting together.

**Comment by zimt28** [comment]
The polyfill seems to be included :)
