### ISSUE TITLE
Apollo ?

### ISSUE THREAD

**Issue by tomitrescak** [kadirahq/meteor-graphql#19]
I'm considering using the GraphQL in my next application, but I'm not sure which way to go. Apollo seems to be in its beginnings with quite complex way of using. This project seems to have much cleaner API. I do not need reactivity, I'm fine with Mantra containers. Would you recommend me your project? If so, what are the disadvantages you see in comparison with Apollo? Thanks

**Comment by arunoda** [comment]
I suggest to go with Apollo(It's not realtime either). 
And it has a simple API which work Mantra without any issue. (without Redux).

**Comment by tomitrescak** [comment]
Hmmm, I gues I'm not good enough. I find Apollo utterly confusing, too many new techniques with no explanation. But I guess I am spoiled by having better docs from Kadira team ;) Is there any plan at all bringin Apollo to Mantra? At least in one of the branches? I think there were multiple requests on that.

**Comment by tomitrescak** [comment]
Your API reads nicely, seems very compatible with Mantra, and does not use extra express server. Galaxy will never know if that express has crashed so I'm affraid for deployment as well. For now I guess I will stick to your solution and I'll create helper classes that will allow me to switch to Apollo once it will stabilise.

**Comment by tomitrescak** [comment]
I made Mantra work with Appollo. Was not that difficult after all, but still, having a nice example to start with would be great ;)
