### ISSUE TITLE
Custom api prefix

### ISSUE THREAD

**Issue by mrphu3074** [kadirahq/meteor-graphql#5]
Hi @arunoda 
i using your package to create apis  for client products.
You package just support only meteor, but i found a tweak to call from client products like 

``` js
import HttpTransport from 'lokka-transport-http';
const transport = new HttpTransport('http://localhost:3003/graphql/ide?schema=SysInfo');
transport.send(`
  {
    sysInfo {
      hostname
    }
  }
`).then(response => {
    console.log(JSON.stringify(response, null, 2));
});
```

so can you publish one more entry point for other client apps? and support ability to change route path ! like `/api`

**Comment by arunoda** [comment]
Haha. That's only available in the debug mode only.
But, we've plan to expose it.
Before that, we need to work on the authentication stuff also with that.
My plan is to use JWT (JSON Web Tokens)

**Comment by mrphu3074** [comment]
:+1:
