### ISSUE TITLE
Use graphql from another meteor server 

### ISSUE THREAD

**Issue by GuyAvraham** [kadirahq/meteor-graphql#8]
I have a meteor server that consume data from another meteor server using graphql.
The Master meteor server has the schema defined,
How can the slave fetch the data using lokka? I dont see a way to define a URL.
Maybe I should use lokka npm directly?

**Comment by arunoda** [comment]
Right now, you need to publish it via `express-graphql` and use Lokka's http transports. But things will be simple soon.

**Comment by GuyAvraham** [comment]
Why not Lokka from npm and meteor kadira:graphql as publisher?

**Comment by arunoda** [comment]
That's a good solution too. We need to work on the way how to deal with authentication. In Meteor we've built in auth support.

**Comment by GuyAvraham** [comment]
So this is why I cannot connect with npm lokka to a publisher with kadira:graphql?? the authentication?
